import {
 mdiAccountOutline,
 mdiCheck,
 mdiCheckCircleOutline,
 mdiChevronRight,
 mdiClipboardListOutline,
 mdiDatabaseExportOutline,
 mdiDeleteOutline,
 mdiDownload,
 mdiEyeOffOutline,
 mdiEyeOutline,
 mdiFileDocumentPlusOutline,
 mdiFileLockOutline,
 mdiFilePlusOutline,
 mdiFileReplace,
 mdiFileReplaceOutline,
 mdiFolderAlertOutline,
 mdiInformationOutline,
 mdiKeyOutline,
 mdiKeyVariant,
 mdiPackageDown,
 mdiPencilOutline,
 mdiRefresh,
 mdiServerNetwork,
 mdiClose,
 mdiCursorPointer,
 mdiAlertCircleOutline,
 mdiAlertOutline,
 mdiRadioboxMarked,
 mdiCheckboxMultipleMarked,
 mdiNumeric,
 mdiCalendar,
 mdiDecimal,
 mdiFormatText,
 mdiImage,
 mdiFileDocumentOutline,
 mdiRepeat,
 mdiLock,
 mdiPencilOffOutline,
 mdiPencilLockOutline,
 mdiAlert,
 mdiArrowUp,
 mdiArrowDown,
 mdiPlus,
 mdiCompassOutline,
 mdiChevronUp,
 mdiTableLock,
 mdiFolderOutline,
 mdiMenuDown,
 mdiDotsVertical,
 mdiCog,
 mdiClipboardTextOutline,
 mdiDragVertical,
 mdiAsterisk,
 mdiCalendarClock,
 mdiClockOutline,
 mdiMapMarker,
 mdiMicrophone,
 mdiTableMultiple,
 mdiShuffleVariant,
 mdiContentSaveOutline, 
  mdiCloseCircle,
  mdiAlertCircle,
  mdiContentSaveAlertOutline,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarked,
  mdiChevronLeft,
  mdiChevronDown,
  mdiCheckCircle,
  mdiPencil,
  mdiTable,
  mdiArrowRight,
  mdiLockOutline,
  mdiFileUploadOutline,
  mdiFolderOpenOutline,
  mdiFileCheckOutline,
  mdiCogOutline,
  mdiCached,
  mdiDownloadCircleOutline,
  mdiMicrosoftExcel,
  mdiFileDelimitedOutline,
  mdiUpload,
  mdiShareVariant,
  mdiDelete  
} from '@mdi/js'
import { defineComponent, h } from 'vue'

// Map mdi-kebab-name → SVG path string
const paths = {
'mdi-account-outline': mdiAccountOutline,
'mdi-check': mdiCheck,
'mdi-check-circle-outline': mdiCheckCircleOutline,
'mdi-chevron-right': mdiChevronRight,
'mdi-clipboard-list-outline': mdiClipboardListOutline,
'mdi-database-export-outline': mdiDatabaseExportOutline,
'mdi-delete-outline': mdiDeleteOutline,
'mdi-download': mdiDownload,
'mdi-eye-off-outline': mdiEyeOffOutline,
'mdi-eye-outline': mdiEyeOutline,
'mdi-file-document-plus-outline': mdiFileDocumentPlusOutline,
'mdi-file-lock-outline': mdiFileLockOutline,
'mdi-file-plus-outline': mdiFilePlusOutline,
'mdi-file-replace': mdiFileReplace,
'mdi-file-replace-outline': mdiFileReplaceOutline,
'mdi-folder-alert-outline': mdiFolderAlertOutline,
'mdi-information-outline': mdiInformationOutline,
'mdi-key-outline': mdiKeyOutline,
'mdi-key-variant': mdiKeyVariant,
'mdi-package-down': mdiPackageDown,
'mdi-pencil-outline': mdiPencilOutline,
'mdi-refresh': mdiRefresh,
'mdi-server-network': mdiServerNetwork,
'mdi-close': mdiClose,
'mdi-cursor-pointer': mdiCursorPointer,
'mdi-alert-circle-outline': mdiAlertCircleOutline,
'mdi-alert-outline': mdiAlertOutline,
'mdi-radiobox-marked': mdiRadioboxMarked,
'mdi-checkbox-multiple-marked': mdiCheckboxMultipleMarked,
'mdi-numeric': mdiNumeric,
'mdi-calendar': mdiCalendar,
'mdi-decimal': mdiDecimal,
'mdi-format-text': mdiFormatText,
'mdi-image': mdiImage,
'mdi-file-document-outline': mdiFileDocumentOutline,
'mdi-repeat': mdiRepeat,
'mdi-lock': mdiLock,
'mdi-pencil-off-outline': mdiPencilOffOutline,
'mdi-pencil-lock-outline': mdiPencilLockOutline,
'mdi-alert': mdiAlert,
'mdi-arrow-up': mdiArrowUp,
'mdi-arrow-down': mdiArrowDown,
'mdi-plus': mdiPlus,
'mdi-compass-outline': mdiCompassOutline,
'mdi-chevron-up': mdiChevronUp,
'mdi-table-lock': mdiTableLock,
'mdi-folder-outline': mdiFolderOutline,
'mdi-menu-down': mdiMenuDown,
'mdi-dots-vertical': mdiDotsVertical,
'mdi-cog': mdiCog,
'mdi-clipboard-text-outline': mdiClipboardTextOutline,
'mdi-drag-vertical': mdiDragVertical,
'mdi-asterisk': mdiAsterisk,
'mdi-calendar-clock': mdiCalendarClock,
'mdi-clock-outline': mdiClockOutline,
'mdi-map-marker': mdiMapMarker,
'mdi-microphone': mdiMicrophone,
'mdi-table-multiple': mdiTableMultiple,
'mdi-shuffle-variant': mdiShuffleVariant,
'mdi-content-save-outline': mdiContentSaveOutline,
'mdi-close-circle': mdiClose,
'mdi-alert-circle': mdiAlertCircleOutline,
'mdi-content-save-alert-outline': mdiContentSaveOutline,
'mdi-checkbox-blank-outline': mdiCheckboxBlankOutline,
'mdi-checkbox-marked': mdiCheckboxMarked,
'mdi-chevron-left': mdiChevronLeft,
'mdi-chevron-down': mdiChevronDown,
'mdi-check-circle': mdiCheckCircle,
'mdi-pencil': mdiPencil,
'mdi-table': mdiTable,
'mdi-arrow-right': mdiArrowRight,
'mdi-lock-outline': mdiLockOutline,
'mdi-file-upload-outline': mdiFileUploadOutline,
'mdi-folder-open-outline': mdiFolderOpenOutline,
'mdi-file-check-outline': mdiFileCheckOutline,
'mdi-cog-outline': mdiCogOutline,
'mdi-cached': mdiCached,
'mdi-download-circle-outline': mdiDownloadCircleOutline,
'mdi-microsoft-excel': mdiMicrosoftExcel,
'mdi-file-delimited-outline': mdiFileDelimitedOutline,
'mdi-upload': mdiUpload,
'mdi-share-variant': mdiShareVariant,
'mdi-delete': mdiDelete

}

const SvgIcon = defineComponent({
 props: ['icon', 'class', 'style'],
 setup(props) {
 return () => {
 const path = paths[props.icon]
 if (import.meta.env.DEV && !path) {
 console.error(`[icons] Unknown icon: "${props.icon}" — add it to src/plugins/icons.js`)
 }
 return h(
 'svg',
 {
 class: ['v-icon__svg', props.class],
 style: { width: '1em', height: '1em', ...(props.style || {}) }, 
 xmlns: 'http://www.w3.org/2000/svg',
 viewBox: '0 0 24 24',
 width: '24px',
 height: '24px',
 role: 'img',
 'aria-hidden': 'true',
 },
 path ? [h('path', { d: path })] : [],
 )
 }
 },
})

// Drop-in custom iconset — receives the raw 'mdi-*' string, no template changes needed
export const customMdi = { component: SvgIcon }